In [47]:
import pandas as pd
import numpy as np

In [48]:
folder = "data/expeditions/expedition_"
dfs=[]
for i in range(30):
    dfs.append(pd.read_csv(folder+str(i)+'.csv', sep=';'))

In [49]:
map_ocean={'0': 'atlantic', #done
          '1': 'atlantic', #done
          '2': 'atlantic', #done
          '3': 'pacific', #done
          '4': 'pacific', #done
          '5': 'pacific', #done
          '6': 'indian', #done
          '7': 'mediterranean', #done
          '8': 'indian', #done
          '9': 'pacific', #done
          '10': 'atlantic', #done
          '11': 'indian', #done
          '12': 'indian', #done
          '13': 'indian', #done
          '14': 'indian', #done
          '15': 'indian', #done
          '16': 'indian', #done
          '17': 'mediterranean', #done
          '18': 'atlantic', #done
          '19': 'indian', #done
          '20': 'indian', #done
          '21': 'atlantic', #done
          '22': 'pacific', #done
          '23': 'pacific', #done
          '24': 'pacific', #done
          '25': 'pacific', #done
          '26': 'pacific', #done
          '27': 'pacific', #done
          '28': 'pacific', #done
          '29': 'pacific' #done 
          }

In [50]:
big_dfs=pd.DataFrame()
for i in range(len(dfs)):
    dfs[i]['ocean'] = map_ocean[str(i)]
    if i==17: dfs[i]=dfs[i].replace('0', np.nan).dropna(subset=['cd1','cd2','cd3','cd4','wd1','wd2','wd3','wd4'], how='all')
    big_dfs = big_dfs.append(dfs[i])  
big_dfs.reset_index(inplace=True, drop=True)

In [51]:
big_dfs['wd1'] = big_dfs['wd1'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['wd2'] = big_dfs['wd2'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['wd3'] = big_dfs['wd3'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['wd4'] = big_dfs['wd4'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['cd1'] = big_dfs['cd1'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['cd2'] = big_dfs['cd2'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['cd3'] = big_dfs['cd3'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))
big_dfs['cd4'] = big_dfs['cd4'].apply(lambda d: float(str(d).replace(' ', '').replace(',',".")))

In [52]:
big_dfs

,Date,Latitude,Longitude,cd1,cd2,cd3,cd4,wd1,wd2,wd3,wd4,SeaState,Source,Info,Comments,Unnamed: 15,ocean
0,09/01/2010,"19,9432","-64,5649",58102.96,21259.89,2226.17,NaN,4.45,26.83,4.23,NaN,"2,5",M. Eriksen,NAG10-SM001,NaN,NaN,atlantic
1,09/01/2010,"20,2173","-64,3828",6639.79,4031.30,1067.11,NaN,1.04,28.69,40.79,NaN,2,M. Eriksen,NAG10-SM002,NaN,NaN,atlantic
2,09/01/2010,"20,4521","-64,1968",15246.71,12147.79,991.66,NaN,2.57,42.62,3503.27,NaN,2,M. Eriksen,NAG10-SM003,NaN,NaN,atlantic
3,10/01/2010,"21,1293","-63,8333",5347.35,6851.29,1420.39,NaN,1.15,12.86,4.26,NaN,2,M. Eriksen,NAG10-SM004,NaN,NaN,atlantic
4,10/01/2010,"21,473","-63,5899",4090.58,5317.76,409.06,NaN,0.48,29.63,4.36,NaN,2,M. Eriksen,NAG10-SM005,NaN,NaN,atlantic
5,10/01/2010,"21,7367","-63,4227",44914.59,46144.76,33133.71,NaN,6.26,47.98,2051.84,NaN,2,M. Eriksen,NAG10-SM006,NaN,NaN,atlantic
6,11/01/2010,"22,15","-63,1474",17324.82,4519.52,502.17,NaN,1.38,3.52,1.13,NaN,2,M. Eriksen,NAG10-SM007,NaN,NaN,atlantic
7,11/01/2010,"22,8418","-62,7592",10467.48,10329.75,413.19,NaN,1.24,33.90,15.84,NaN,2,M. Eriksen,NAG10-SM008,NaN,NaN,atlantic
8,12/01/2010,"24,3576","-62,8129",7434.53,9436.14,190.63,NaN,1.14,28.59,0.29,NaN,4,M. Eriksen,NAG10-SM009,NaN,NaN,atlantic
9,12/01/2010,"24,3576","-62,8129",0.00,1510.37,704.84,NaN,0.00,8.96,13.59,NaN,4,M. Eriksen,NAG10-SM010,NaN,NaN,atlantic
10,13/01/2010,"24,7657","-62,7221",377.59,1636.23,377.59,NaN,0.11,5.41,7.93,NaN,4,M. Eriksen,NAG10-SM011,NaN,NaN,atlantic
11,13/01/2010,"25,3751","-62,4785",3126.56,2918.12,416.87,NaN,0.46,3.99,0.42,NaN,3,M. Eriksen,NAG10-SM012,NaN,NaN,atlantic
12,13/01/2010,"25,5607","-62,4387",428395.48,132757.97,119370.62,NaN,15.62,837.83,25752.82,NaN,2,M. Eriksen,NAG10-SM013,NaN,NaN,atlantic
13,14/01/2010,"26,0914","-61,7168",0.00,2111.27,351.88,NaN,0.00,4.52,8.45,NaN,"4,5",M. Eriksen,NAG10-SM014,NaN,NaN,atlantic
14,15/01/2010,"29,249","-62,9857",4682.38,14983.63,1560.79,NaN,0.61,86.00,105.82,NaN,"2,5",M. Eriksen,NAG10-SM015,NaN,NaN,atlantic
15,15/01/2010,"29,7453","-63,2167",3020.74,35544.01,3725.58,NaN,0.41,165.27,613.71,NaN,2,M. Eriksen,NAG10-SM016,NaN,NaN,atlantic
16,16/01/2010,"30,5477","-63,7064",31985.11,157152.30,4991.90,NaN,8.10,778.18,599.95,NaN,2,M. Eriksen,NAG10-SM017,NaN,NaN,atlantic
17,17/01/2010,"31,1813","-64,0147",1173.82,10137.53,1814.08,NaN,0.45,47.17,101.16,NaN,"2,5",M. Eriksen,NAG10-SM018,NaN,NaN,atlantic
18,17/01/2010,"31,535","-64,2677",9953.75,31224.77,2590.70,NaN,1.50,135.67,67.49,NaN,2,M. Eriksen,NAG10-SM019,NaN,NaN,atlantic
19,18/01/2010,"31,9644","-64,5448",4082.42,24984.39,2776.04,NaN,0.65,154.97,1465.26,NaN,2,M. Eriksen,NAG10-SM020,NaN,NaN,atlantic
20,10/11/2010,"-26,4261","-41,0363",0.00,1973.57,845.81,NaN,0.00,5.47,1.41,NaN,4,M. Eriksen,SAG10-14,NaN,NaN,atlantic
21,11/11/2010,"-26,3881","-39,9167",363.39,5087.42,1453.55,NaN,0.03,29.00,10.97,NaN,4,M. Eriksen,SAG10-15,NaN,NaN,atlantic
22,11/11/2010,"-26,1893","-38,7646",503.15,2515.76,503.15,NaN,0.25,11.22,25.84,NaN,4,M. Eriksen,SAG10-16,NaN,NaN,atlantic
23,12/11/2010,"-26,131","-37,5873",0.00,4862.50,540.28,NaN,0.00,31.74,57.16,NaN,4,M. Eriksen,SAG10-17,NaN,NaN,atlantic
24,12/11/2010,"-25,9968","-36,4999",3400.01,8985.73,485.72,NaN,0.31,51.56,40.53,NaN,4,M. Eriksen,SAG10-18,NaN,NaN,atlantic
25,13/11/2010,"-25,8957","-35,3693",1962.29,3270.48,654.10,NaN,0.36,6.87,11.05,NaN,3,M. Eriksen,SAG10-19,NaN,NaN,atlantic
26,13/11/2010,"-25,801","-34,2127",0.00,14090.91,0.00,NaN,0.00,84.96,0.00,NaN,3,M. Eriksen,SAG10-20,NaN,NaN,atlantic
27,14/11/2010,"-25,9165","-35,0814",1206.33,6433.74,4423.19,NaN,0.44,10.86,50.59,NaN,3,M. Eriksen,SAG10-21,NaN,NaN,atlantic
28,14/11/2010,"-26,0782","-31,973",0.00,8328.91,0.00,NaN,0.00,80.11,0.00,NaN,3,M. Eriksen,SAG10-22,NaN,NaN,atlantic
29,16/11/2010,"-26,3129","-31,0914",1022.03,7767.40,817.62,NaN,0.04,57.58,122.87,NaN,3,M. Eriksen,SAG10-23,NaN,NaN,atlantic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,25/07/2009,"37,4833","-142,1",NaN,NaN,NaN,5.33,NaN,NaN,NaN,6109.85,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
795,26/07/2009,"37,85",-138,NaN,NaN,NaN,0.61,NaN,NaN,NaN,277.21,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
796,25/07/2009,"29,7333","-150,6167",NaN,NaN,NaN,10.45,NaN,NaN,NaN,4750.31,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
797,26/07/2009,"31,0667","-148,8",NaN,NaN,NaN,9.23,NaN,NaN,NaN,8854.48,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
798,27/07/2009,"32,5667","-147,4167",NaN,NaN,NaN,4.51,NaN,NaN,NaN,3879.38,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
799,28/07/2009,"34,4333","-145,8167",NaN,NaN,NaN,5.31,NaN,NaN,NaN,3546.05,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
800,29/07/2009,"36,5","-144,9",NaN,NaN,NaN,9.21,NaN,NaN,NaN,7447.62,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
801,30/07/2009,"37,9667","-143,4833",NaN,NaN,NaN,8.32,NaN,NaN,NaN,4459.81,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
802,30/07/2009,"27,5667","-157,3833",NaN,NaN,NaN,1.20,NaN,NaN,NaN,89.44,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
803,21/07/2009,"30,95","-157,35",NaN,NaN,NaN,1.57,NaN,NaN,NaN,694.34,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
804,22/07/2009,"33,4","-156,9333",NaN,NaN,NaN,5.75,NaN,NaN,NaN,4463.17,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
805,23/07/2009,"34,5","-153,25",NaN,NaN,NaN,5.41,NaN,NaN,NaN,2189.57,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
806,24/07/2009,"35,4167","-149,8833",NaN,NaN,NaN,5.47,NaN,NaN,NaN,4397.28,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
807,25/07/2009,36,"-146,3333",NaN,NaN,NaN,5.17,NaN,NaN,NaN,2131.34,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
808,26/07/2009,"36,5","-142,0833",NaN,NaN,NaN,8.36,NaN,NaN,NaN,1794.93,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
809,27/07/2009,"37,1667","-138,9167",NaN,NaN,NaN,0.73,NaN,NaN,NaN,1009.66,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
810,28/07/2009,"37,15","-138,9",NaN,NaN,NaN,0.49,NaN,NaN,NaN,24.56,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
811,19/08/2009,"22,4217","-159,5167",NaN,NaN,NaN,0.44,NaN,NaN,NaN,26.42,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
812,20/08/2009,"24,6667","-159,4667",NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
813,21/08/2009,"27,4852","-158,3032",NaN,NaN,NaN,4.11,NaN,NaN,NaN,315.54,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
814,23/08/2009,"32,346","-157,5991",NaN,NaN,NaN,9.24,NaN,NaN,NaN,4870.07,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
815,24/08/2009,"33,9533","-155,8267",NaN,NaN,NaN,20.71,NaN,NaN,NaN,8941.12,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
816,25/08/2009,"35,8667","-152,5333",NaN,NaN,NaN,12.58,NaN,NaN,NaN,9651.00,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
817,27/08/2009,"37,0717","-148,6533",NaN,NaN,NaN,13.01,NaN,NaN,NaN,5246.81,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
818,28/08/2009,"36,1333","-142,15",NaN,NaN,NaN,587.33,NaN,NaN,NaN,108840.82,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
819,29/08/2009,"35,5483","-139,4417",NaN,NaN,NaN,8.22,NaN,NaN,NaN,4800.05,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
820,30/08/2009,"34,8083","-136,82",NaN,NaN,NaN,2.75,NaN,NaN,NaN,549.35,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
821,31/08/2009,"34,5883","-133,7417",NaN,NaN,NaN,0.89,NaN,NaN,NaN,832.35,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
822,01/09/2009,"34,7433","-131,535",NaN,NaN,NaN,0.50,NaN,NaN,NaN,25.08,NaN,H. Carson,ENPG 2009,NaN,NaN,pacific
823,02/09/2009,"34,6683","-129,1617",NaN,NaN,NaN,0.52,NaN,NaN,NaN,1058.45,NaN,H. Carson,ENPG 2009,43,NaN,pacific

In [90]:
big_dfs = big_dfs.fillna(0)
grouped = big_dfs.groupby(['ocean'])
final = pd.DataFrame(grouped.mean())
final['max_w'] = final[['wd1', 'wd2', 'wd3', 'wd4']].max().max()
final['max_c'] = final[['cd1', 'cd2', 'cd3', 'cd4']].max().max()

In [91]:
final[['cd1_r', 'cd2_r', 'cd3_r', 'cd4_r']] = np.sqrt(final[['cd1', 'cd2', 'cd3', 'cd4']]/final['max_c']['atlantic'])
final[['wd1_r', 'wd2_r', 'wd3_r', 'wd4_r']] = np.sqrt(final[['wd1', 'wd2', 'wd3', 'wd4']]/final['max_w']['atlantic'])
final.to_csv('ocean_overview.csv')

In [92]:
final

,cd1,cd2,cd3,cd4,wd1,wd2,wd3,wd4,max_w,max_c
ocean,,,,,,,,,,
atlantic,0.853501,1.000000,0.411301,0.001481,0.058086,0.239602,0.450475,0.066371,2286.117885,35903.645402
indian,0.143823,0.324119,0.159452,0.012179,0.006066,0.050457,0.232935,0.600145,2286.117885,35903.645402
mediterranean,0.554683,0.418384,0.299496,0.010883,0.000000,0.000000,0.000000,0.249292,2286.117885,35903.645402
pacific,0.495814,0.660433,0.214754,0.014936,0.024558,0.145881,0.351791,1.000000,2286.117885,35903.645402